# config.yaml

api:
  key: "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"  # Replace with your actual API key
  model: "gpt-4o-mini"
  url: "https://api.openai.com/v1/chat/completions"

paths:
  stakes_file: "data/GPS_stakes_by_country_2018-05-04.xlsx"
  output_folder: "data/processed/"
  gps_folder: "data/processed/gps2/"

countries:
  - "Germany"
  - "Afghanistan"
  - "Algeria"
  - "Argentina"
  - "Australia"
  - "Austria"
  - "Bangladesh"
  - "Bolivia"
  - "Bosnia"
  - "Brazil"
  - "Cambodia"
  - "Cameroon"
  - "Canada"
  - "Chile"
  - "China"
  - "Colombia"
  - "Costa Rica"
  - "Croatia"
  - "Czech Republic"
  - "Egypt"
  - "Estonia"
  - "Finland"
  - "France"
  - "Georgia"
  - "Ghana"
  - "Greece"
  - "Guatemala"
  - "Hungary"
  - "India"
  - "Indonesia"
  - "Iran"
  - "Iraq"
  - "Israel"
  - "Italy"
  - "Japan"
  - "Jordan"
  - "Kazakhstan"
  - "Kenya"
  - "Lithuania"
  - "Mexico"
  - "Moldova"
  - "Morocco"
  - "Netherlands"
  - "Nicaragua"
  - "Nigeria"
  - "Pakistan"
  - "Peru"
  - "Philippines"
  - "Poland"
  - "Portugal"
  - "Romania"
  - "Russia"
  - "Rwanda"
  - "Saudi Arabia"
  - "Serbia"
  - "South Africa"
  - "South Korea"
  - "Spain"
  - "Sri Lanka"
  - "Sweden"
  - "Switzerland"
  - "Tanzania"
  - "Thailand"
  - "Turkey"
  - "Uganda"
  - "Ukraine"
  - "United Arab Emirates"
  - "United Kingdom"
  - "United States"
  - "Venezuela"
  - "Vietnam"
  - "Zimbabwe"
  - "Botswana"
  - "Haiti"
  - "Malawi"
  - "Suriname"
  - "None"

country_currency_dict:
  Germany: "EUR"
  Afghanistan: "AFN"
  Algeria: "DZD"
  Argentina: "ARS"
  Australia: "AUD"
  Austria: "EUR"
  Bangladesh: "BDT"
  Bolivia: "BOB"
  Bosnia: "BAM"
  Brazil: "BRL"
  Cambodia: "KHR"
  Cameroon: "XAF"
  Canada: "CAD"
  Chile: "CLP"
  China: "CNY"
  Colombia: "COP"
  Costa Rica: "CRC"
  Croatia: "HRK"
  "Czech Republic": "CZK"
  Egypt: "EGP"
  Estonia: "EUR"
  Finland: "EUR"
  France: "EUR"
  Georgia: "GEL"
  Ghana: "GHS"
  Greece: "EUR"
  Guatemala: "GTQ"
  Hungary: "HUF"
  India: "INR"
  Indonesia: "IDR"
  Iran: "IRR"
  Iraq: "IQD"
  Israel: "ILS"
  Italy: "EUR"
  Japan: "JPY"
  Jordan: "JOD"
  Kazakhstan: "KZT"
  Kenya: "KES"
  Lithuania: "EUR"
  Mexico: "MXN"
  Moldova: "MDL"
  Morocco: "MAD"
  Netherlands: "EUR"
  Nicaragua: "NIO"
  Nigeria: "NGN"
  Pakistan: "PKR"
  Peru: "PEN"
  Philippines: "PHP"
  Poland: "PLN"
  Portugal: "EUR"
  Romania: "RON"
  Russia: "RUB"
  Rwanda: "RWF"
  "Saudi Arabia": "SAR"
  Serbia: "RSD"
  "South Africa": "ZAR"
  "South Korea": "KRW"
  Spain: "EUR"
  "Sri Lanka": "LKR"
  Sweden: "SEK"
  Switzerland: "CHF"
  Tanzania: "TZS"
  Thailand: "THB"
  Turkey: "TRY"
  Uganda: "UGX"
  Ukraine: "UAH"
  "United Arab Emirates": "AED"
  "United Kingdom": "GBP"
  "United States": "USD"
  Venezuela: "VES"
  Vietnam: "VND"
  Zimbabwe: "ZWL"
  Botswana: "BWP"
  Haiti: "HTG"
  Malawi: "MWK"
  Suriname: "SRD"
  None: ""

settings:
  num_samples_per_country_gender: 1
  semaphore_limit: 10
  max_retries: 3